Toolranks compat, translations, and refactoring
minetest-mods/glooptest pull request #3
Opened 2020-02-18 22:28 UTC by louisroyer

This is a big PR, but some translati
Fix GloopMaster/issues/3

Note: This uses new feature of toolranks from lisacvuk/minetest-toolranks/pull/11 do not merge in glooptest until this PR is merged in toolranks.

Add translation support and french translation for `ore_module` and `tools_module`

2020-09-17 17:37 UTC, SmallJoker requested changes
Not backwards compatible by default.
:ballot_box_with_check: Lumps, ingots, blocks
:negative_squared_cross_mark: 
:negative_squared_cross_mark:

2020-09-18 05:57 UTC, louisroyer commented
> Not backwards compatible by default.
> ballot_box_with_check Lumps, ingots, blocks are registered
> ballot_box_with_check Gems are registered
> negative_squared_cross_mark Alatro tools seem to be missing entirely
> 
> Left: PR, Right: master
> ![grafik](https://user-images.githubusercontent.com/1497498/93507528-1da66280-f91e-11ea-8f06-81db4f15d2cb.png)

I accidentally had removed tool definitions for Alatro and Arol. This should be fixed now, but I don't have the time to test this change today.

2025-06-03 17:04 UTC, Niklp09 commented
@wsor4035 asked me to review this.

My patch to fix tool registration (Not sure how to force any changes on this branch…)
```diff
diff --git a/init.lua b/init.lua
index da040f7..f3a057f 100644
--- a/init.lua
+++ b/init.lua
@@ -28,14 +28,14 @@ function glooptest.debug(level,message)
 	print("["..level.."][GloopTest v0.0.4a] "..message)
 end
 
-if glooptest.modules.ore then
-	dofile(minetest.get_modpath("glooptest").."/ore_module/init.lua")
+if glooptest.modules.tools then
+	dofile(minetest.get_modpath("glooptest").."/tools_module/init.lua")
 	local modulecount = modules_loaded
 	modules_loaded = modulecount+1
 end
 
-if glooptest.modules.tools then
-	dofile(minetest.get_modpath("glooptest").."/tools_module/init.lua")
+if glooptest.modules.ore then
+	dofile(minetest.get_modpath("glooptest").."/ore_module/init.lua")
 	local modulecount = modules_loaded
 	modules_loaded = modulecount+1
 end
diff --git a/ore_module/api.lua b/ore_module/api.lua
index 7f57c9e..9240792 100644
--- a/ore_module/api.lua
+++ b/ore_module/api.lua
@@ -83,14 +83,16 @@ function glooptest.ore_module.register_ore(modname, name, desc, uses)
 		end
 	end
 	-- register tools
-	if glooptest.modules.tools and (uses.tools ~= nil) and (uses.tools.makes ~= nil) then
+	if glooptest.modules.tools and (uses.tools ~= nil) and (uses.tools.make ~= nil) then
 		local u = {}
-		for tool, value in pairs(uses.tools.makes) do
-			u[tool].makes = value
-			u[tool].texture = uses.tools.texture[tool] or nil
-			u[tool].caps = uses.tools.caps[tool] or nil
-			u[tool].desc = uses.tools.desc[tool] or nil
+		for tool, value in pairs(uses.tools.make) do
+			u[tool] = {
+				makes = value,
+				texture = uses.tools.texture[tool] or nil,
+				caps = uses.tools.caps[tool] or nil,
+				desc = uses.tools.desc[tool] or nil,
+			}
 		end
-		glooptest.tools_module.register_tools(modname, name, desc, u)
+		glooptest.tools_module.register_tools(modname, name, desc, name.."_ingot", u)
 	end
 end
diff --git a/ore_module/init.lua b/ore_module/init.lua
index 3f8953f..23d6ecb 100644
--- a/ore_module/init.lua
+++ b/ore_module/init.lua
@@ -147,6 +147,7 @@ glooptest.ore_module.register_ore("glooptest", "alatro", nil, {
 			sword = S("Alatro Sword"),
 			axe = S("Alatro Axe"),
 			pick = S("Alatro Pickaxe"),
+			shovel = S("Alatro Shovel"),
 			handsaw = S("Alatro Handsaw"),
 			hammer = S("Alatro Hammer"),
 		},
```

All items are present (two more on page 2)
![image](https://github.com/user-attachments/assets/69d4aaa8-373d-43b2-af99-24ddd0625b32)

I avoided rebuilding the translation files for the time being to not make the comment too long.
LGTM otherwise.

2025-06-03 18:10 UTC, SmallJoker commented
LGTM. Will merge in a few days unless there are objections.
I also noticed that is mod has plenty of issues revealed by luacheck, which I will address later on.

2025-06-03 18:11 UTC, SmallJoker approved these changes

2025-06-03 18:54 UTC, Niklp09 commented
>  I also noticed that is mod has plenty of issues revealed by luacheck, which I will address later on.

I've noticed this too, I already fixed some stuff locally.
Btw: Are you able to activate the issue tracker? I only have the permission to commit.

2025-06-06 14:35 UTC, merged